[notion]
api_key = ""

[webhook]
host = "0.0.0.0"
port = 3000
secret = ""
max_age_seconds = 300

[key_map]
# "Name" = "title"
# "Tags" = "tags"
# "Published" = "published"

[[database]]
id = "xxxxxxxxxxxxxxxx"
[[database.storage]]
type = "fs"
root = "/tmp/db1"

[database.key_map]
# "Name" = "title"
# "Tags" = "tags"
# "Published" = "published"

# [[database]]
# id = "yyyyyyyyyyyyyyyy"
# [[database.storage]]
# type = "s3"
# bucket = "your-bucket"
# region = "us-east-1"
# access_key_id = "AKIA..."
# secret_access_key = "..."
# endpoint = "https://s3.amazonaws.com"
