[notion]
api_key = ""

[webhook]
host = "0.0.0.0"
port = 3000
secret = ""
max_age_seconds = 300

[database.db1]
id = "xxxxxxxxxxxxxxxx"
[database.db1.storage]
type = "fs"
root = "/tmp/db1"

# [database.db2]
# id = "yyyyyyyyyyyyyyyy"
# [database.db2.storage]
# type = "s3"
# bucket = "your-bucket"
# region = "us-east-1"
# access_key_id = "AKIA..."
# secret_access_key = "..."
# endpoint = "https://s3.amazonaws.com"
